# Generated by Django 5.0.4 on 2026-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
