# Generated by Django 5.0.4 on 2026-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_rename_altitude_product_tea_altitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasetemplate",
            name="show_toggle_list",
            field=models.BooleanField(default=True),
        ),
    ]
